version: '3.8'

services:
  app:
    image: paccy/procure-to-pay
    container_name: backend
    env_file:
      - .env
    depends_on:
      procure-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - procure-net

  procure-db:
    image: postgres:15
    container_name: procure-database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - procure-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d procure_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name:  database-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: procure@example.com
      PGADMIN_DEFAULT_PASSWORD: procure
    ports:
      - "7070:80"
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - procure-net
    profiles:
      - debug

volumes:
  postgres_data:
  pgadmin_data:
networks:
  procure-net:
    driver: bridge