spring:
  application:
    name: Procure-to-Pay
    version: 1.0
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api-docs

security:
  jwt:
    expiration: 86400000
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    refresh-token:
      expiration: 604800000
    super-admin: ${SECURITY_JWT_SUPER_ADMIN}