spring:
  application:
    name: Procure-to-Pay
    version: 1.0
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  ai:
    ollama:
      chat:
        options:
          temperature: 0.0
          model: gemma3:1b
    retry:
      max-attempts: 4

logging:
  level:
    root: info
    web: error
    com.pacifique.security.review.controller: debug

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET-KEY}
    expiration: 86400000
    refresh-token:
      expiration: 604800000
    admin: ${SECURITY_JWT_SUPER-ADMIN}

springdoc:
  swagger-ui:
    path: /api-docs
cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: ${CLOUDINARY_NAME}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DOCKER_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: info
    org.commitlink.procure.services: debug
    org.commitlink.procure.controller: debug
